/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-tertiary-container": "#b8e0ff",
              "surface-container": "#eceef0",
              "tertiary-fixed": "#c9e6ff",
              "tertiary": "#004d70",
              "inverse-surface": "#2d3133",
              "outline-variant": "#c7c4d8",
              "on-surface": "#191c1e",
              "primary-container": "#4f46e5",
              "on-primary-fixed": "#0f0069",
              "outline": "#777587",
              "surface-dim": "#d8dadc",
              "on-secondary-fixed": "#25005a",
              "on-primary-container": "#dad7ff",
              "on-tertiary-fixed-variant": "#004c6e",
              "primary-fixed-dim": "#c3c0ff",
              "on-secondary": "#ffffff",
              "primary-fixed": "#e2dfff",
              "surface-container-low": "#f2f4f6",
              "on-secondary-fixed-variant": "#5a00c6",
              "on-tertiary-fixed": "#001e2f",
              "surface-container-high": "#e6e8ea",
              "primary": "#3525cd",
              "surface": "#f7f9fb",
              "error": "#ba1a1a",
              "on-error": "#ffffff",
              "tertiary-container": "#006693",
              "secondary-container": "#8a4cfc",
              "inverse-on-surface": "#eff1f3",
              "on-primary-fixed-variant": "#3323cc",
              "on-error-container": "#93000a",
              "on-tertiary": "#ffffff",
              "secondary-fixed-dim": "#d2bbff",
              "on-secondary-container": "#fffbff",
              "on-background": "#191c1e",
              "background": "#f7f9fb",
              "surface-variant": "#e0e3e5",
              "secondary-fixed": "#eaddff",
              "on-primary": "#ffffff",
              "error-container": "#ffdad6",
              "surface-tint": "#4d44e3",
              "tertiary-fixed-dim": "#89ceff",
              "secondary": "#712ae2",
              "surface-container-lowest": "#ffffff",
              "on-surface-variant": "#464555",
              "surface-bright": "#f7f9fb",
              "surface-container-highest": "#e0e3e5",
              "inverse-primary": "#c3c0ff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px",
              "28px": "28px"
      },
      "maxWidth": {
              "container-max-width": "1280px"
      },
      "spacing": {
              "gutter-mobile": "16px",
              "gutter-desktop": "24px",
              "unit": "8px",
              "margin-mobile": "16px",
              "margin-desktop": "32px",
              "container-max-width": "1280px"
      },
      "fontFamily": {
              "label-lg": ["Hanken Grotesk"],
              "display-lg": ["Hanken Grotesk"],
              "title-lg": ["Hanken Grotesk"],
              "headline-lg-mobile": ["Hanken Grotesk"],
              "body-lg": ["Hanken Grotesk"],
              "headline-lg": ["Hanken Grotesk"],
              "label-md": ["Hanken Grotesk"],
              "body-md": ["Hanken Grotesk"],
              "title-md": ["Hanken Grotesk"],
              "sans": ["Hanken Grotesk", "sans-serif"]
      },
      "fontSize": {
              "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1px", "fontWeight": "500"}],
              "display-lg": ["57px", {"lineHeight": "64px", "letterSpacing": "-0.25px", "fontWeight": "400"}],
              "title-lg": ["22px", {"lineHeight": "28px", "fontWeight": "500"}],
              "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
              "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0.5px", "fontWeight": "400"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
              "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.5px", "fontWeight": "500"}],
              "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.25px", "fontWeight": "400"}],
              "title-md": ["16px", {"lineHeight": "24px", "letterSpacing": "0.15px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
